###################################################
# Build images
###################################################
- block:
  - name: Build mongo image
    docker_image:
      build:
        path: "{{ role_path }}/files/mongo"
        pull: yes
      source: build
      name: "{{ mongo_graylog_image }}:{{ mongo_docker_tag }}"
      repository: "{{ acr_address }}/{{ mongo_graylog_image }}:{{ mongo_docker_tag }}"
      force_source: yes
      
  - name: Build elasticsearch image
    docker_image:
      build:
        path: "{{ role_path }}/files/elastic"
        pull: no
      source: build
      name: "{{ es_graylog_image }}:{{ es_docker_tag }}"
      repository: "{{ acr_address }}/{{ es_graylog_image }}:{{ es_docker_tag }}"
      force_source: yes

  - name: Build graylog image
    docker_image:
      build:
        path: "{{ role_path }}/files/graylog"
        pull: no
      source: build
      name: "{{ docker_graylog_image }}:{{ graylog_docker_tag }}"
      repository: "{{ acr_address }}/{{ docker_graylog_image }}:{{ graylog_docker_tag }}"
      force_source: yes

  tags:
  - build
