- block:
  - name: Log into private registry
    docker_login:
      registry: "{{ acr_address }}"
      username: "{{ vault_acr_builder_principal_id }}"
      password: "{{ vault_acr_builder_principal_pass }}"
        
  - name: Push images mongo    
    docker_image:
      name: "{{ item }}"
      push: yes
      source: local
    with_items:
      - "{{ acr_address }}/{{ mongo_graylog_image }}:{{ mongo_docker_tag }}"

  - name: Push images elasticsearch
    docker_image:
      name: "{{ item }}"
      push: yes
      source: local
    with_items:
      - "{{ acr_address }}/{{ es_graylog_image }}:{{ es_docker_tag }}"

  - name: Push images graylog
    docker_image:
      name: "{{ item }}"
      push: yes
      source: local
    with_items:
      - "{{ acr_address }}/{{ docker_graylog_image }}:{{ graylog_docker_tag }}"

  tags: always
