###################################################
# Build images
###################################################
- block:
  - name: change work directory Prometheus installation files
    command: chdir="{{ role_path }}/files/kafka-consumer-lag-monitoring" sh buildall.sh 
    
  - name: Build Kafka-lag image
    docker_image:
      build:
        path: "{{ role_path }}/files/kafka-consumer-lag-monitoring"
        pull: no               
      source: build
      name: "{{ kafka_lag_image }}:{{ kafka_lag_docker_tag }}"
      repository: "{{ acr_address }}/{{ kafka_lag_image }}:{{ kafka_lag_docker_tag }}"
      force_source: yes

  - name: change work directory timescaledb installation files
    command: chdir="{{ role_path }}/files/prometheus/timescaledb-docker" ls 
    
  - name: Build timescaledb image
    docker_image:
      build:
        path: "{{ role_path }}/files/prometheus/timescaledb-docker"
        pull: no       
        args: 
          PG_VERSION: 10.5             
      source: build
      name: "{{ timescaledb_image }}:{{ timescaledb_docker_tag }}"
      repository: "{{ acr_address }}/{{ timescaledb_image }}:{{ timescaledb_docker_tag }}"
      force_source: yes

  - name: change work directory pg_prometheus installation files
    command: chdir="{{ role_path }}/files/prometheus/pg_prometheus" ls 
    
  - name: Build pg_prometheus image
    docker_image:
      build:
        path: "{{ role_path }}/files/prometheus/pg_prometheus"
        pull: no       
        args: 
          PG_VERSION_TAG: pg10             
      source: build
      name: "{{ pg_prometheus_image }}:{{ pg_prometheus_docker_tag }}"
      repository: "{{ acr_address }}/{{ pg_prometheus_image }}:{{ pg_prometheus_docker_tag }}"
      force_source: yes
      
  - name: change work directory prometheus_postgresql_adapter installation files
    command: chdir="{{ role_path }}/files/prometheus/prometheus-postgresql-adapter" ls 
    
  - name: Build prometheus_postgresql_adapter image
    docker_image:
      build:
        path: "{{ role_path }}/files/prometheus/prometheus-postgresql-adapter"
        pull: no       
      source: build
      name: "{{ prometheus_postgresql_adapter_image }}:{{ prometheus_postgresql_adapter_docker_tag }}"
      repository: "{{ acr_address }}/{{ prometheus_postgresql_adapter_image }}:{{ prometheus_postgresql_adapter_docker_tag }}"
      force_source: yes

  - name: change work directory prometheus files
    command: chdir="{{ role_path }}/files/prometheus/prometheus" ls 
    
  - name: Build prometheus image
    docker_image:
      build:
        path: "{{ role_path }}/files/prometheus/prometheus"
        pull: no       
      source: build
      name: "{{ prometheus_image }}:{{ prometheus_docker_tag }}"
      repository: "{{ acr_address }}/{{ prometheus_image }}:{{ prometheus_docker_tag }}"
      force_source: yes
                
  tags:
  - build
