### Setup server
---
- hosts: servers
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - server
  tasks:
    - name: Debug
      debug: msg="{{ ansible_run_tags }}"
      tags:
        - always