version: '2'
services:
  pg_prometheus:
    image: pg_prometheus:latest
    container_name: pg_prometheus
    hostname: pg_prometheus
    network_mode: host
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    command: postgres -c synchronous_commit=off
    volumes:
      - /storage/pgdata:/var/lib/postgresql/data
    logging:
      options:
        max-size: 50m
  prometheus_postgresql_adapter:
    image: prometheus-postgresql-adapter:latest
    container_name: prometheus_postgresql_adapter
    hostname: prometheus_postgresql_adapter
    network_mode: host
    restart: on-failure
    extra_hosts:
      - "pg_prometheus:127.0.0.1"
    environment:
      - TS_PROM_PG_PASSWORD=postgres
    depends_on:
      - pg_prometheus
    command:
      - '-pg-host=pg_prometheus'
      - '-pg-port=5433'
    logging:
      options:
        max-size: 50m      
  prometheus:
    image: prometheus:latest
    container_name: prometheus
    hostname: prometheus
    network_mode: host
    restart: on-failure
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - /data/prometheus_data:/prometheus 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - pg_prometheus
      - prometheus_postgresql_adapter
    extra_hosts:
      - "pg_prometheus:127.0.0.1"
      - "prometheus_postgresql_adapter:127.0.0.1"
      - "kafka-lag:127.0.0.1"
