#-------------------------------------------------------
#Server variables
#-------------------------------------------------------
server_1: 10.1.2.50
server_2: 10.1.2.60
server_3: 10.1.2.70
server_4: 172.19.40.9
sshd_port: 9122

#-------------------------------------------------------
# User variables
#-------------------------------------------------------
default_user: spale
default_group: spale
user_owner: spale
acr_address: mspasic
default_password: Loz08042011
#-------------------------------------------------------
# Consul variables
#-------------------------------------------------------
consul_1: "{{server_1}}"
consul_2: "{{server_2}}"
consul_3: "{{server_3}}"
consul_nodes: [ "{{server_1}}", "{{server_2}}", "{{server_3}}" ]
consul_port: 8500

#-------------------------------------------------------
# Zookeeper variables
#-------------------------------------------------------
zoo_nodes: [ "{{server_1}}", "{{server_2}}", "{{server_3}}" ]
zookeeper_servers: "{{server_1}}:2181,{{server_2}}:2181,{{server_3}}:2181"

#-------------------------------------------------------
# Kafka variables
#-------------------------------------------------------
kafka_port: 9092
kafka_broker_1: "{{server_1}}"
kafka_broker_2: "{{server_2}}"
kafka_broker_3: "{{server_3}}"
kafka_nodes: [ "{{server_1}}", "{{server_2}}", "{{server_3}}" ]

#-------------------------------------------------------
# Greenplum variables
#-------------------------------------------------------
gp_port: 5434
gpcc_port: 28080
gp_db_name: silbodb
gp_user: silbo
gp_master_ip: "{{server_1}}"
gp_standby_ip: "{{server_4}}"
gp_postgis: postgis-2.1.5+pivotal.2-7-gp6-rhel7-x86_64.gppkg
gp_plr: plr-3.0.3-gp6-rhel7-x86_64.gppkg
gp_cc: greenplum-cc-web-6.0.0-rhel7_x86_64
gp_cc_ver: 6.0.0
gp_backup: pivotal_greenplum_backup_restore-1.15.0-1-gp6-rhel-x86_64.gppkg
gp_data_directory_primary: /var/lib/gpdb/data/primary /var/lib/gpdb/data/primary /var/lib/gpdb/data/primary
gp_data_directory_mirror: /var/lib/gpdb/data/mirror /var/lib/gpdb/data/mirror /var/lib/gpdb/data/mirror
gp_workers: { 'gp_db_seg_1' }
gp_servers:
  gp_db_master:
    role: master
    nodeip: "{{server_1}}"
  gp_db_seg_1:
    role: slave
    nodeip: "{{server_2}}"
  gp_db_standby:
    role: slave
    nodeip: "{{server_3}}"

#-------------------------------------------------------
# Haproxy variables
#-------------------------------------------------------
haproxy_ip: "{{server_4}}"

#-------------------------------------------------------
# Basic variables
#-------------------------------------------------------

locale: en_US.UTF-8
timezone: UTC

#-------------------------------------------------------
# General
#-------------------------------------------------------
volume_ssd: /containers # SSD faster disk drive
volume_hdd: /data/containers # HDD slower disk drive

