consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/COLOREDLOGS_LOG_FORMAT "%(asctime)s %(message)s"
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/COLOREDLOGS_LEVEL_STYLES "spam=22;debug=28;verbose=34;notice=220;warning=220;success=118,bold;error=124;critical=220"
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/PAUSED ""
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/INITIAL ""
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/TOPIC ""
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/EXCLUDE "smartivodb.public.dashboard_company,smartivodb.public.dashboard_locationrecord,smartivodb.public.test,smartivodb.public.nova,smartivodb.public.spatial_ref_sys,smartivodb.public.daily_event,smartivodb.public.geozone"
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/KAFKA_SERVER "kafka:9092"
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/DBNAME smartivodb2
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/DATABASE smartivodb
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/USER smartivodb
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/PASS password
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/DBPORT 5432
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/DBSERVER "127.0.0.1"
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/TABLE ""
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/BULK 20000
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/BULK_STAGING 500000
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/CONSUMER_GROUP pg2gp
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/EXCEPTIONS "{ "smartivodb.public.dashboard_drivingstats" : {"Primary_keys" : "id", "Distribution_keys" : "driving_id"},"smartivodb.public.dashboard_driving" :{"Primary_keys" : "id", "Distribution_keys" : "id"},"smartivodb.public.dashboard_locationrecord" : {"Primary_keys" : "id", "Distribution_keys" : "id"},"smartivodb.public.django_session" : {"Primary_keys" : "session_key", "Distribution_keys" : ""},"smartivodb.public.dashboard_drivingoverspeed" : {"Primary_keys" : "id", "Distribution_keys" : "driving_id"},"smartivodb.public.dashboard_fuelrecord" : {"Primary_keys" : "id", "Distribution_keys" : "location_record_id"},"smartivodb.public.dashboard_drivingpois" :{"Primary_keys" : "id", "Distribution_keys" : "driving_id"},"smartivodb.public.dashboard_temperaturerecord" : {"Primary_keys" : "id", "Distribution_keys" : "location_record_id"},"smartivodb.public.dashboard_fmsrecord" : {"Primary_keys" : "id", "Distribution_keys" : "location_record_id"},"smartivodb.public.dashboard_garminstatus" : {"Primary_keys" : "id", "Distribution_keys" : "vehicle_id"},"smartivodb.public.dashboard_ecorecord" : {"Primary_keys" : "id", "Distribution_keys" : "location_record_id"}}"
consul kv put -http-addr=127.0.0.1:8500 SMARTIVODB2/STAGING_TABLES "smartivodb.public.dashboard_fmsrecord,smartivodb.public.dashboard_driving,smartivodb.public.dashboard_ecorecord,smartivodb.public.dashboard_fuelrecord,smartivodb.public.dashboard_drivingstats,smartivodb.public.dashboard_drivingpois,smartivodb.public.dashboard_dailytemperature,smartivodb.public.dashboard_dailyvehicledrivers,smartivodb.public.dashboard_temperaturerecord,smartivodb.public.dashboard_drivingoverspeed"