- block:
  - name: Add Docker key
    apt_key:
      keyserver: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes
      state: present

  - name: Log into private registry
    docker_login:
      username: "{{ vault_acr_principal_id }}"
      password: "{{ vault_acr_principal_pass }}"

  - name: Pull images pg_prometheus
    docker_image:
      name: "{{ item }}"
      source: pull
    with_items:
      - "{{ pg_prometheus_image }}:{{ pg_prometheus_docker_tag }}"

  - name: Pull images prometheus_postgresql_adapter
    docker_image:
      name: "{{ item }}"
      source: pull
    with_items:
      - "{{ prometheus_postgresql_adapter_image }}:{{ prometheus_postgresql_adapter_docker_tag }}"

  - name: Pull images prometheus
    docker_image:
      name: "{{ item }}"
      source: pull
    with_items:
      - "{{ prometheus_image }}:{{ prometheus_docker_tag }}"

  - name: Pull images kafka_lag
    docker_image:
      name: "{{ item }}"
      source: pull
    with_items:
      - "{{ kafka_lag_image }}:{{ kafka_lag_docker_tag }}"

  tags: always
