- block:
               
  - name: Check data folders exist
    file: name={{ item }} state=directory
    with_items:
      - "{{ consul_data_folder }}"
      - "{{ consul_conf_folder }}"
      - "{{ consul_tmp_folder }}"
      - "{{ consul_script_folder }}"

  - name: Change file ownership, group and permissions
    file: name={{ item }} owner=smartivo group=smartivo mode='0777'
    with_items:
      - "{{ consul_data_folder }}"
      - "{{ consul_conf_folder }}"  
      - "{{ consul_tmp_folder }}"
               
  - name: Copy configs
    template: src=templates/{{ item }} dest={{ consul_conf_folder }}/{{ item }}
    with_items:
      - config.json

  - name: Copy configs
    template: src=templates/{{ item }} dest={{ consul_tmp_folder }}/{{ item }}
    with_items:
      - createkv.sh

  - name: Changing perm of "/tmp/*.sh", adding "+x"
    file: dest={{ consul_tmp_folder }}/{{ item }} mode=a+x      
    with_items:
      - createkv.sh
                  
  - name: Check server container running
    shell: docker inspect {{ consul_tag }} | grep Running
    register: server_running
    ignore_errors: True

  - name: Stop server container
    shell: docker stop {{ consul_tag }}
    ignore_errors: True
    when: "'true' in server_running.stdout"

  - name: Create consul container
    shell: docker run 
      --rm 
      --name={{ consul_tag }} 
      --detach=true
      --network="host"
      -v {{ consul_conf_folder }}/config.json:/consul/config/local.json
      -v {{ consul_data_folder }}:/consul/data 
      "{{ acr_address }}/{{ docker_consul_image }}:{{ consul_docker_tag }}"
      agent -node={{ private_ip }} -config-dir=/consul/config
    register: result 

  - name: Save start script
    copy: content={{ result.cmd }} dest={{ consul_script_folder }}/start_{{ consul_tag }}.sh mode=a+x 
      
  tags: always
 